### Register User
POST https://notes-backend-akbar-13926268988.us-central1.run.app/register
Content-Type: application/json

{
    "name": "tes",
    "password": "12"
}

### Login User
POST https://notes-backend-akbar-13926268988.us-central1.run.app/login
Content-Type: application/json

{
    "name": "tes",
    "password": "12"
}

### Get Notes
GET https://notes-backend-akbar-13926268988.us-central1.run.app/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJuYW1lIjoiYWppIiwiaWF0IjoxNzQ3MTQ5NTIyLCJleHAiOjE3NDcxNDk1NTJ9.3Rvkvz5XptRzobJJgHf0eFtKOY3saFvH9d1aiTI1I-g

### Create Note
POST http://localhost:3000/notes/add-notes
Content-Type: application/json
Authorization: Bearer notesvelte12345

{
    "judul": "Test Note",
    "deskripsi": "This is a test note",
    "kategori": "Test"
}

### Get Single Note
GET http://localhost:5000/notes/1
Authorization: Bearer YOUR_ACCESS_TOKEN

### Update Note
PUT http://localhost:5000/notes/update-notes/3
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN

{
    "judul": "Updated Note",
    "deskripsi": "This note has been updated",
    "kategori": "Updated"
}

### Delete Note
DELETE http://localhost:5000/notes/1
Authorization: Bearer YOUR_ACCESS_TOKEN

### Logout
DELETE http://localhost:5000/logout